# -*- coding: utf-8 -*-
"""Tugas10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12V_s808PgsWcOCMCZYvY8sDS3Wmwj3CN
"""

hasil_akhir = [
  {'nama':'Afif', 'nilai':70},
  {'nama':'Fauzi', 'nilai':63},
  {'nama':'Rofiq', 'nilai':80},
  {'nama':'Faiz', 'nilai':40}
]

def predikatlulus(data):
    lulus = [mahasiswa['nama']
        for mahasiswa in data
        if mahasiswa['nilai'] > 65]
    return lulus

hasil = predikatlulus(hasil_akhir)
print('mahasiswa yang lulus ialah', hasil)

daftar_buah = ["pepaya", "mangga", "pisang", "durian", "jambu"]

def list_buah(buah):
    list_terbalik = []

    for x in range(len(buah) -1, -1, -1):
        list_terbalik.append(buah[x])
    return list_terbalik

hasil_terbalik = list_buah(daftar_buah)
print('Ini hasilnya',hasil_terbalik)

daftar_buah = ['pepaya', 'mangga', 'pisang', 'durian', 'jambu']

def list_buah(buah):
    buah_duplikasi = []

    for a in buah:
        buah_duplikasi.append(a)
        buah_duplikasi.append(a)
    return buah_duplikasi


hasil_duplikasi = list_buah(daftar_buah)
print('Inilah hasilnya: ', hasil_duplikasi)

def list_huruf(huruf):
    hapus_huruf = ''

    for n in huruf:
      if n not in 'aiueo':
        hapus_huruf += n

    return hapus_huruf


daftar_huruf = konsonan('Nurul Fikri')
print('hasilnya adalah: ', daftar_huruf)